from tkinter import*
root=Tk()
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry=('%dx%d+0+0'%(w,h))
img=PhotoImage(file=".\\Bus_for_project.png")
Label(root,image=img).grid(row=0,column=3,columnspan=3)
Label(root,text='Online Bus Booking System',font='Arial 14 bold',bg='light blue',fg='red').grid(row=2,column=3,pady=15,columnspan=3)
Label(root,text='Add Bus Operator Details',font='Arial 14 bold',bg='grey97',fg='dark green').grid(row=3,column=3,pady=20,columnspan=3)
Label(root,text='operator id').grid(row=4,column=0)
Entry(root,font='Arial 14 bold').grid(row=4,column=1)
Label(root,text='Name').grid(row=4,column=2)
Entry(root,font='Arial 14 bold').grid(row=4,column=3)
Label(root,text='Address').grid(row=4,column=4)
Entry(root,font='Arial 14 bold').grid(row=4,column=5)
Label(root,text='Phone').grid(row=4,column=6)
Entry(root,font='Arial 14 bold').grid(row=4,column=7)
Label(root,text='Email').grid(row=4,column=8)
Entry(root,font='Arial 14 bold').grid(row=4,column=9)
Button(root,text='Add',bg='light green',fg='dark green').grid(row=4,column=10)
Button(root,text='Edit',bg='light green',fg='dark green').grid(row=4,column=11,pady=30)
immg=PhotoImage(file="home.png")
Button(root,image=immg).grid(row=5,column=8)

root.mainloop()
